import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface CoaLabSample {
  brix?: number | null;
  ph?: number | null;
  ta?: number | null;
  va?: number | null;
  alcohol?: number | null;
  so2_free?: number | null;
  so2_total?: number | null;
  rs?: number | null;
  sampled_at?: string | null;
}

export interface CoaTrial {
  name: string;
  notes?: string | null;
}

export interface CoaReportData {
  vintageYear: number | string;
  blockName: string;
  vineyardName: string;
  status: string;
  harvestDate?: string | null;
  latestLab: CoaLabSample | null;
  trials: CoaTrial[];
  generatedAt: Date;
}

const CRIMSON: [number, number, number] = [107, 27, 42];
const GOLD: [number, number, number] = [200, 144, 42];
const CREAM: [number, number, number] = [245, 240, 232];
const GRAY: [number, number, number] = [102, 102, 102];
const DARK: [number, number, number] = [33, 33, 33];

const PAGE_W = 8.5;
const PAGE_H = 11;
const MARGIN = 0.75;

function safeFilename(s: string): string {
  return s.replace(/\s+/g, "_").replace(/[^A-Za-z0-9_.-]/g, "");
}

function drawHeader(doc: jsPDF, title: string, subtitle: string): void {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...GOLD);
  doc.text("SOLERA", MARGIN, 0.55);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text("Certificate of Analysis", MARGIN + 0.95, 0.55);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...DARK);
  doc.text(title, PAGE_W - MARGIN, 0.45, { align: "right" });
  doc.setTextColor(...GRAY);
  doc.text(subtitle, PAGE_W - MARGIN, 0.62, { align: "right" });

  doc.setDrawColor(...CRIMSON);
  doc.setLineWidth(0.014);
  doc.line(MARGIN, 0.78, PAGE_W - MARGIN, 0.78);
}

function drawFooter(doc: jsPDF, pageNum: number, pageCount: number): void {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text("Generated by Solera - solera.vin", PAGE_W / 2, PAGE_H - 0.4, { align: "center" });
  doc.text(`Page ${pageNum} of ${pageCount}`, PAGE_W - MARGIN, PAGE_H - 0.4, { align: "right" });
}

export function exportCoaPdf(report: CoaReportData): void {
  const doc = new jsPDF({ unit: "in", format: "letter", orientation: "portrait" });
  const title = `${report.vintageYear} ${report.blockName}`.trim();
  const subtitle = report.vineyardName || "";

  drawHeader(doc, title, subtitle);

  let y = 1.05;
  doc.setFont("times", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...CRIMSON);
  doc.text("Certificate of Analysis", MARGIN, y);
  y += 0.35;

  // Metadata block
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...DARK);
  const metaLines = [
    `Vintage: ${report.vintageYear}`,
    `Block: ${report.blockName || "—"}`,
    `Vineyard: ${report.vineyardName || "—"}`,
    `Status: ${report.status || "—"}`,
  ];
  if (report.harvestDate) metaLines.push(`Harvest Date: ${report.harvestDate}`);
  for (const line of metaLines) {
    doc.text(line, MARGIN, y);
    y += 0.22;
  }

  y += 0.15;

  // Lab values table
  doc.setFont("times", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...CRIMSON);
  doc.text("Final Lab Values", MARGIN, y);
  y += 0.15;

  const lab = report.latestLab;
  const labRows: (string | number)[][] = [];
  if (lab) {
    if (lab.brix != null) labRows.push(["Brix", `${lab.brix}°`]);
    if (lab.ph != null) labRows.push(["pH", String(lab.ph)]);
    if (lab.ta != null) labRows.push(["TA", String(lab.ta)]);
    if (lab.va != null) labRows.push(["VA", String(lab.va)]);
    if (lab.alcohol != null) labRows.push(["Alcohol", `${lab.alcohol}%`]);
    if (lab.so2_free != null) labRows.push(["Free SO2", String(lab.so2_free)]);
    if (lab.so2_total != null) labRows.push(["Total SO2", String(lab.so2_total)]);
    if (lab.rs != null) labRows.push(["RS", String(lab.rs)]);
  }
  if (labRows.length === 0) labRows.push(["No lab data available", ""]);

  autoTable(doc, {
    startY: y,
    head: [["Parameter", "Value"]],
    body: labRows,
    theme: "grid",
    margin: { top: 0.95, left: MARGIN, right: MARGIN, bottom: 0.6 },
    styles: { font: "helvetica", fontSize: 10, cellPadding: 0.08, lineColor: [220, 220, 220], lineWidth: 0.005, textColor: DARK },
    headStyles: { fillColor: CRIMSON, textColor: [255, 255, 255], fontStyle: "bold" },
    alternateRowStyles: { fillColor: CREAM },
    didDrawPage: () => drawHeader(doc, title, subtitle),
  });
  // @ts-expect-error lastAutoTable is added by the plugin
  y = (doc.lastAutoTable.finalY as number) + 0.3;

  // Blends
  if (report.trials.length > 0) {
    doc.setFont("times", "bold");
    doc.setFontSize(14);
    doc.setTextColor(...CRIMSON);
    doc.text("Blend Composition", MARGIN, y);
    y += 0.2;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...DARK);
    for (const t of report.trials) {
      const line = t.notes ? `${t.name} - ${t.notes}` : t.name;
      doc.text(line, MARGIN, y);
      y += 0.22;
    }
    y += 0.2;
  }

  // Signature block
  if (y > PAGE_H - 1.6) {
    doc.addPage();
    drawHeader(doc, title, subtitle);
    y = 1.2;
  }
  y += 0.4;
  doc.setDrawColor(...DARK);
  doc.setLineWidth(0.008);
  doc.line(MARGIN, y, MARGIN + 3, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text("Facility Signature", MARGIN, y + 0.2);

  doc.text(
    `Generated ${report.generatedAt.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}`,
    PAGE_W - MARGIN,
    y + 0.2,
    { align: "right" },
  );

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    drawFooter(doc, i, pageCount);
  }

  const filename = `COA_${safeFilename(String(report.vintageYear))}_${safeFilename(report.blockName || "Vintage")}.pdf`;
  doc.save(filename);
}