import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export interface TtbReportData {
  org: {
    name: string;
    bonded_winery_number?: string | null;
    proprietor_name?: string | null;
    bond_number?: string | null;
  };
  period: { start: string; end: string; label: string };
  summary: {
    totalWineProduced: number;
    totalWineRemoved: number;
    inventoryOnHand: number;
    bondBalance: number;
  };
  additions: Array<{
    date: string;
    type: string;
    quantity: number;
    unit: string;
    lotVessel: string;
    notes: string;
  }>;
  taxAndBond: Array<{
    taxClass: string;
    gallonsRemoved: number;
    taxRate: number;
    taxDue: number;
  }>;
  generatedAt: Date;
}

const CRIMSON: [number, number, number] = [107, 27, 42];
const GOLD: [number, number, number] = [200, 144, 42];
const CREAM: [number, number, number] = [245, 240, 232];
const GRAY: [number, number, number] = [102, 102, 102];
const DARK: [number, number, number] = [33, 33, 33];

const PAGE_W = 8.5;
const PAGE_H = 11;
const MARGIN = 0.75;

function fmtNumber(n: number, decimals = 2): string {
  return n.toLocaleString("en-US", {
    minimumFractionDigits: decimals,
    maximumFractionDigits: decimals,
  });
}

function fmtCurrency(n: number): string {
  return n.toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
  });
}

function safeFilename(s: string): string {
  return s.replace(/\s+/g, "_").replace(/[^A-Za-z0-9_.-]/g, "");
}

function drawHeader(
  doc: jsPDF,
  orgName: string,
  periodLabel: string,
): void {
  // SOLERA mark, gold, small caps style (helvetica bold + letter spacing visual)
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...GOLD);
  doc.text("SOLERA", MARGIN, 0.55);

  // Subtitle in gray
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text("TTB Compliance Report", MARGIN + 0.95, 0.55);

  // Right side: org + period
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...DARK);
  doc.text(orgName, PAGE_W - MARGIN, 0.45, { align: "right" });
  doc.setTextColor(...GRAY);
  doc.text(periodLabel, PAGE_W - MARGIN, 0.62, { align: "right" });

  // Crimson rule
  doc.setDrawColor(...CRIMSON);
  doc.setLineWidth(0.014); // ~1pt
  doc.line(MARGIN, 0.78, PAGE_W - MARGIN, 0.78);
}

function drawFooter(doc: jsPDF, pageNum: number, pageCount: number): void {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text(
    "Generated by Solera - solera.vin",
    PAGE_W / 2,
    PAGE_H - 0.4,
    { align: "center" },
  );
  doc.text(
    `Page ${pageNum} of ${pageCount}`,
    PAGE_W - MARGIN,
    PAGE_H - 0.4,
    { align: "right" },
  );
}

function drawStatBox(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  label: string,
  value: string,
): void {
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.008);
  doc.roundedRect(x, y, w, h, 0.06, 0.06, "S");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...GRAY);
  doc.text(label.toUpperCase(), x + 0.15, y + 0.28);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(...DARK);
  doc.text(value, x + 0.15, y + 0.7);
}

function applyAutoTable(
  doc: jsPDF,
  startY: number,
  head: string[][],
  body: (string | number)[][],
  foot: (string | number)[][] | undefined,
  orgName: string,
  periodLabel: string,
): number {
  autoTable(doc, {
    startY,
    head,
    body,
    foot,
    theme: "grid",
    margin: { top: 0.95, left: MARGIN, right: MARGIN, bottom: 0.6 },
    styles: {
      font: "helvetica",
      fontSize: 9,
      cellPadding: 0.08,
      lineColor: [220, 220, 220],
      lineWidth: 0.005,
      textColor: DARK,
    },
    headStyles: {
      fillColor: CRIMSON,
      textColor: [255, 255, 255],
      fontStyle: "bold",
      fontSize: 9,
    },
    alternateRowStyles: {
      fillColor: CREAM,
    },
    footStyles: {
      fillColor: [240, 240, 240],
      textColor: DARK,
      fontStyle: "bold",
    },
    didDrawPage: () => {
      drawHeader(doc, orgName, periodLabel);
    },
  });
  // @ts-expect-error lastAutoTable is added by the plugin
  return doc.lastAutoTable.finalY as number;
}

export function exportTtbReportPdf(report: TtbReportData): void {
  const doc = new jsPDF({ unit: "in", format: "letter", orientation: "portrait" });
  const orgName = report.org.name || "Winery";
  const periodLabel = report.period.label;

  drawHeader(doc, orgName, periodLabel);

  // Page 1 — Summary
  let y = 1.05;
  doc.setFont("times", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...CRIMSON);
  doc.text("Operations Report - OW-1", MARGIN, y);
  y += 0.35;

  // 2x2 stat grid
  const gridX = MARGIN;
  const gridY = y;
  const gridW = PAGE_W - MARGIN * 2;
  const cellW = (gridW - 0.2) / 2;
  const cellH = 0.95;

  drawStatBox(
    doc, gridX, gridY, cellW, cellH,
    "Total Wine Produced",
    `${fmtNumber(report.summary.totalWineProduced)} gal`,
  );
  drawStatBox(
    doc, gridX + cellW + 0.2, gridY, cellW, cellH,
    "Total Wine Removed",
    `${fmtNumber(report.summary.totalWineRemoved)} gal`,
  );
  drawStatBox(
    doc, gridX, gridY + cellH + 0.2, cellW, cellH,
    "Inventory on Hand",
    `${fmtNumber(report.summary.inventoryOnHand)} gal`,
  );
  drawStatBox(
    doc, gridX + cellW + 0.2, gridY + cellH + 0.2, cellW, cellH,
    "Bond Balance",
    fmtCurrency(report.summary.bondBalance),
  );

  y = gridY + cellH * 2 + 0.4 + 0.15;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text(
    `Generated ${report.generatedAt.toLocaleDateString("en-US", {
      year: "numeric", month: "long", day: "numeric",
    })} - ${orgName}`,
    MARGIN,
    y,
  );

  // Additions section
  y += 0.4;
  doc.setFont("times", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...CRIMSON);
  doc.text("Additions and Adjustments", MARGIN, y);
  y += 0.15;

  const additionsBody: (string | number)[][] = report.additions.length
    ? report.additions.map((a) => [
        a.date,
        a.type,
        fmtNumber(a.quantity, 2),
        a.unit,
        a.lotVessel,
        a.notes,
      ])
    : [["No additions recorded for this period", "", "", "", "", ""]];

  applyAutoTable(
    doc,
    y,
    [["Date", "Type", "Quantity", "Unit", "Lot/Vessel", "Notes"]],
    additionsBody,
    undefined,
    orgName,
    periodLabel,
  );

  // Page break for Tax and Bond
  doc.addPage();
  drawHeader(doc, orgName, periodLabel);
  y = 1.05;
  doc.setFont("times", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...CRIMSON);
  doc.text("Tax and Bond Summary", MARGIN, y);
  y += 0.15;

  const taxBody: (string | number)[][] = report.taxAndBond.length
    ? report.taxAndBond.map((r) => [
        r.taxClass,
        fmtNumber(r.gallonsRemoved),
        fmtCurrency(r.taxRate),
        fmtCurrency(r.taxDue),
      ])
    : [["No taxable removals recorded", "", "", ""]];

  const totalGallons = report.taxAndBond.reduce((s, r) => s + r.gallonsRemoved, 0);
  const totalTax = report.taxAndBond.reduce((s, r) => s + r.taxDue, 0);
  const taxFoot: (string | number)[][] | undefined = report.taxAndBond.length
    ? [["Total", fmtNumber(totalGallons), "", fmtCurrency(totalTax)]]
    : undefined;

  applyAutoTable(
    doc,
    y,
    [["Tax Class", "Gallons Removed", "Tax Rate", "Tax Due"]],
    taxBody,
    taxFoot,
    orgName,
    periodLabel,
  );

  // Footer pass on every page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    drawFooter(doc, i, pageCount);
  }

  const filename = `TTB_Report_${safeFilename(orgName)}_${safeFilename(periodLabel)}.pdf`;
  doc.save(filename);
}

export function exportTtbAdditionsPdf(
  orgName: string,
  from: string,
  to: string,
  additions: TtbReportData["additions"],
): void {
  const doc = new jsPDF({ unit: "in", format: "letter", orientation: "portrait" });
  const periodLabel = `${from} to ${to}`;

  drawHeader(doc, orgName || "Winery", periodLabel);

  let y = 1.05;
  doc.setFont("times", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...CRIMSON);
  doc.text("Additions Log", MARGIN, y);
  y += 0.35;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text(
    `Generated ${new Date().toLocaleDateString("en-US", {
      year: "numeric", month: "long", day: "numeric",
    })} - ${orgName}`,
    MARGIN,
    y,
  );
  y += 0.3;

  const body: (string | number)[][] = additions.length
    ? additions.map((a) => [
        a.date,
        a.type,
        fmtNumber(a.quantity, 2),
        a.unit,
        a.lotVessel,
        a.notes,
      ])
    : [["No additions recorded for this period", "", "", "", "", ""]];

  applyAutoTable(
    doc,
    y,
    [["Date", "Type", "Quantity", "Unit", "Lot/Vessel", "Notes"]],
    body,
    undefined,
    orgName || "Winery",
    periodLabel,
  );

  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    drawFooter(doc, i, pageCount);
  }

  const filename = `TTB_Additions_${safeFilename(orgName || "Winery")}_${safeFilename(from)}_to_${safeFilename(to)}.pdf`;
  doc.save(filename);
}
