import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import { FileText, Download, Loader2, Sparkles, RefreshCw } from "lucide-react";
import { format, parseISO } from "date-fns";
import { useState } from "react";
import { toast } from "sonner";
import ReactMarkdown from "react-markdown";

export default function Reports() {
  const { organization } = useAuth();
  const orgId = organization?.id;
  const [generating, setGenerating] = useState(false);

  const { data: summaries = [], isLoading, refetch } = useQuery({
    queryKey: ["weekly-summaries", orgId],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("weekly_summaries")
        .select("*")
        .order("week_starting", { ascending: false })
        .limit(52);
      if (error) throw error;
      return data;
    },
    enabled: !!orgId,
  });

  const handleGenerateNow = async () => {
    setGenerating(true);
    try {
      const { data: { session } } = await supabase.auth.getSession();
      const resp = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/weekly-summary`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${session?.access_token}`,
        },
        body: JSON.stringify({ orgId }),
      });
      if (!resp.ok) throw new Error("Failed to generate summary");
      toast.success("Weekly summary generated!");
      refetch();
    } catch (e: any) {
      toast.error(e.message || "Failed to generate summary");
    } finally {
      setGenerating(false);
    }
  };

  const handleDownloadPdf = (summary: any) => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      toast.error("Please allow popups to download PDF");
      return;
    }

    const weekEnd = new Date(summary.week_starting);
    weekEnd.setDate(weekEnd.getDate() + 6);

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Solera Weekly Summary — ${format(parseISO(summary.week_starting), "MMM d, yyyy")}</title>
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Playfair+Display:wght@700&family=Source+Sans+3:wght@400;600&display=swap');
          body { font-family: 'Source Sans 3', sans-serif; max-width: 700px; margin: 40px auto; padding: 0 20px; color: #1a1a1a; }
          .header { display: flex; align-items: center; gap: 16px; margin-bottom: 24px; border-bottom: 2px solid #5e1d31; padding-bottom: 16px; }
          .header h1 { font-family: 'Playfair Display', serif; font-size: 24px; color: #5e1d31; margin: 0; }
          .header .subtitle { font-size: 14px; color: #666; margin: 4px 0 0; }
          .ai-badge { display: inline-flex; align-items: center; gap: 4px; background: #f0f0f0; border-radius: 12px; padding: 2px 10px; font-size: 11px; color: #666; }
          .content { line-height: 1.7; font-size: 14px; }
          .content h1, .content h2, .content h3 { font-family: 'Playfair Display', serif; color: #5e1d31; }
          .content h2 { font-size: 18px; margin-top: 24px; }
          .content ul { padding-left: 20px; }
          .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 12px; color: #999; }
          @media print { body { margin: 20px; } }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1>Solera Weekly Summary</h1>
            <p class="subtitle">${organization?.name || "Winery"} — Week of ${format(parseISO(summary.week_starting), "MMMM d, yyyy")}</p>
          </div>
        </div>
        <div style="margin-bottom: 16px;"><span class="ai-badge">✨ AI Generated</span></div>
        <div class="content">${summary.content.replace(/\n/g, "<br>")}</div>
        <div class="footer">Generated by Solera on ${format(parseISO(summary.generated_at), "MMMM d, yyyy 'at' h:mm a")}</div>
      </body>
      </html>
    `);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 500);
  };

  if (isLoading) {
    return <div className="flex items-center justify-center h-64"><Loader2 className="h-6 w-6 animate-spin text-muted-foreground" /></div>;
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl md:text-3xl font-display font-bold text-foreground">Reports</h1>
          <p className="text-muted-foreground mt-1">AI-generated weekly winery summaries</p>
        </div>
        <Button onClick={handleGenerateNow} disabled={generating} variant="outline">
          {generating ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <RefreshCw className="h-4 w-4 mr-2" />}
          Generate Now
        </Button>
      </div>

      {summaries.length === 0 ? (
        <Card>
          <CardContent className="py-12 text-center">
            <FileText className="h-10 w-10 text-muted-foreground mx-auto mb-3" />
            <p className="text-muted-foreground">No weekly summaries yet. They are generated automatically every Monday, or click "Generate Now".</p>
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-4">
          {summaries.map((summary: any) => (
            <Card key={summary.id}>
              <CardHeader>
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <CardTitle className="text-lg font-display">
                      Week of {format(parseISO(summary.week_starting), "MMMM d, yyyy")}
                    </CardTitle>
                    <p className="text-xs text-muted-foreground mt-1">
                      Generated {format(parseISO(summary.generated_at), "MMM d, yyyy 'at' h:mm a")}
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    <Badge variant="outline" className="text-[10px] gap-1 shrink-0">
                      <Sparkles className="h-3 w-3" /> AI
                    </Badge>
                    <Button size="sm" variant="outline" onClick={() => handleDownloadPdf(summary)}>
                      <Download className="h-4 w-4 mr-1" /> PDF
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="prose prose-sm max-w-none text-foreground">
                  <ReactMarkdown>{summary.content}</ReactMarkdown>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
