REVOKE EXECUTE ON FUNCTION public.auto_expire_contracts() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_default_alert_rules() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_grape_cost_from_weigh_tag() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.enforce_user_count_limit() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_client_org_id_for_user(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_conversation_org_id(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_facility_org_id(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_import_job_org_id(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_org_tier(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_sheet_connection_org_id(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_shipment_org_id(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_trial_org_id(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_user_org_id(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_vessel_org_id(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_vineyard_org_id(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_vintage_org_id(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_webhook_sub_org_id(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.increment_roadmap_votes() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.org_has_tier(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.protect_client_user_role() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.protect_profile_role() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.recalculate_lot_cost_summary() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.update_contract_totals() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.void_grape_cost_on_unapprove() FROM PUBLIC;

GRANT EXECUTE ON FUNCTION public.get_client_org_id_for_user(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_conversation_org_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_facility_org_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_import_job_org_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_org_tier(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_sheet_connection_org_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_shipment_org_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_trial_org_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_user_org_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_vessel_org_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_vineyard_org_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_vintage_org_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_webhook_sub_org_id(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_role(uuid, public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.org_has_tier(uuid, text) TO authenticated;

ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;